---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 85148.
--- DateTime: 2025/8/7 17:16
---
local FightingMgr = require('Fighting/FightingMgr')
login = {}

function login.Update()
   print('这是登录脚本')
   FightingMgr.Update()
end

return login