---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 85148.
--- DateTime: 2025/8/7 17:28
---

FightingMgr ={}

function FightingMgr.Update()
    print('这是战斗脚本')

end
return FightingMgr