--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 85148.
--- DateTime: 2025/8/7 16:48
--Lua脚本的入口
--local login = require('UI/Login')
--local UIMainView = require('DiYiTao/UI/UIMainView')
--local UIRewardView = require('DiErTao/UIRewardView')
--local UIMainView = require('DiSanTao/UIMainView')

--local UIMainView = require('DiSiTao/UIMainView') --加载
local UIMainView = require('DiLiuTao/UIMainPanel')
function Update()
    --UIRewardView:Update()
end